### ISSUE TITLE
A minor issue in the examples

### ISSUE THREAD

**Issue by rogerwwww** [javajawa/check-registry-for-image#1]
Hi there,

Many thanks for providing this helpful tool! 

I discover a minor issue in the example in README.

The current version is:
```
    if: ${{ steps.existing-image.outputs.exists == 'false' }}
```

But it should be:
```
    if: ${{ steps.existing-image.outputs.exists == false }}
```
without the single quotes.

**Comment by javajawa** [comment]
Hello!

Weirdly, due to the underlying protocol, the quotes are ""correct"".
The output method is actually writing a specially formatted string to the logs[1, 2] so the `false` gets coerced to `'false'`.

That being said, it would not surprise me if the same type conversion happens in the `if` statement, so both versions will work.

(Note: I have not actively tested this!)

[1] https://github.com/actions/toolkit/blob/a502af875/packages/core/src/core.ts#L190-L193
[2] https://github.com/actions/toolkit/blob/a502af875/packages/core/src/command.ts#L23-L30

**Comment by rogerwwww** [comment]
Hi there,

Thanks for your timely response!

I double-checked my Github Action logs and I found there is a mistake in my own config. I would say the example is correct with quotes and does not work without quotes.
